Update workflow

diff --git a/plugins/source/gcp/Makefile b/plugins/source/gcp/Makefile
--- a/plugins/source/gcp/Makefile
+++ b/plugins/source/gcp/Makefile
@@ -18,13 +18,17 @@ lint:
 
 .PHONY: gen-docs
 gen-docs: build
-	cd ../../../cli && go build -o cli && cd -
-	../../../cli/cli tables --format json --output-dir ./docs test/config.yml
+	@command -v cloudquery >/dev/null 2>&1 || { \
+		echo "Error: 'cloudquery' command not found. Please install it before running gen-docs."; \
+		echo "You can install it by following the instructions at: https://www.cloudquery.io/docs/quickstart"; \
+		exit 1; \
+	}
+	cloudquery tables --format json --output-dir ./docs test/config.yml
 	go run scripts/policy_docs/main.go gcp policies ../../../website/pages/docs/plugins/sources/gcp/policies.md docs/gcp/__tables.json
 	rm docs/gcp/__tables.json
 
 	rm -rf ../../../website/tables/gcp
-	../../../cli/cli tables --format markdown --output-dir ../../../website/tables test/config.yml
+	cloudquery tables --format markdown --output-dir ../../../website/tables test/config.yml
 	go run scripts/example_queries/main.go policies/queries ../../../website/tables/gcp
 	sed 's_(\(.*\))_(../../../../../website/tables/gcp/\1)_' ../../../website/tables/gcp/README.md > ./docs/tables/README.md
 	sed -i.bak -e 's_(\(.*\).md)_(tables/\1)_' ../../../website/tables/gcp/README.md
