Update workflow

diff --git a/plugins/source/alicloud/Makefile b/plugins/source/alicloud/Makefile
--- a/plugins/source/alicloud/Makefile
+++ b/plugins/source/alicloud/Makefile
@@ -32,9 +32,13 @@ gen-mocks:
 
 .PHONY: gen-docs
 gen-docs: build
-	cd ../../../cli && go build -o cli && cd -
+	@command -v cloudquery >/dev/null 2>&1 || { \
+		echo "Error: 'cloudquery' command not found. Please install it before running gen-docs."; \
+		echo "You can install it by following the instructions at: https://www.cloudquery.io/docs/quickstart"; \
+		exit 1; \
+	}
 	rm -rf ../../../website/tables/alicloud
-	../../../cli/cli tables --format markdown --output-dir ../../../website/tables test/config.yml
+	cloudquery tables --format markdown --output-dir ../../../website/tables test/config.yml
 	sed 's_(\(.*\))_(../../../../../website/tables/alicloud/\1)_' ../../../website/tables/alicloud/README.md > ./docs/tables/README.md
 	sed -i.bak -e 's_(\(.*\).md)_(tables/\1)_' ../../../website/tables/alicloud/README.md
 	mv ../../../website/tables/alicloud/README.md ../../../website/pages/docs/plugins/sources/alicloud/tables.md
