Update workflows

diff --git a/plugins/source/aws/Makefile b/plugins/source/aws/Makefile
--- a/plugins/source/aws/Makefile
+++ b/plugins/source/aws/Makefile
@@ -3,10 +3,6 @@
 test:
 	go test -race -timeout 3m ./...
 
-.PHONY: build
-build:
-	go build -o aws
-
 # Install tools
 .PHONY: install-tools
 install-tools:
@@ -27,14 +23,18 @@ gen-mocks:
 	go run client/mockassert/main.go
 
 .PHONY: gen-docs
-gen-docs: build
-	cd ../../../cli && go build -o cli && cd -
-	../../../cli/cli tables --format json --output-dir ./docs test/config.yml
+gen-docs:
+	@command -v cloudquery >/dev/null 2>&1 || { \
+		echo "Error: 'cloudquery' command not found. Please install it before running gen-docs."; \
+		echo "You can install it by following the instructions at: https://www.cloudquery.io/docs/quickstart"; \
+		exit 1; \
+	}
+	cloudquery tables --format json --output-dir ./docs test/config.yml
 	go run scripts/policy_docs/main.go aws policies ../../../website/pages/docs/plugins/sources/aws/policies.md docs/aws/__tables.json
 	rm docs/aws/__tables.json
 
 	rm -rf ../../../website/tables/aws
-	../../../cli/cli tables --format markdown --output-dir ../../../website/tables test/config.yml
+	cloudquery tables --format markdown --output-dir ../../../website/tables test/config.yml
 	go run scripts/example_queries/main.go policies/queries ../../../website/tables/aws
 	sed 's_(\(.*\))_(../../../../../website/tables/aws/\1)_' ../../../website/tables/aws/README.md > ./docs/tables/README.md
 	sed -i.bak -e 's_(\(.*\).md)_(tables/\1)_' ../../../website/tables/aws/README.md
